#!/bin/sh

# Place in /usr/local/bin/apt-proxy-autodetect
# Make it executable: chmod +x /usr/local/bin/apt-proxy-autodetect

# APT passes a URL as $1 (we ignore it). Output either proxy URL or DIRECT.

# Only works for HTTP URLs

## Variables to configure
# our LAN gateway IP address -- if we are not using it, we are likely not on our LAN
# even if the PROXY is reachable (through a VPN or other Tailscale subnet router),
# we are not on our LAN and we should not use the proxy
LAN_GATEWAY="10.0.0.1"
# if you LAN_IP uses static reservation, we can use it in addition to the gateway
# keep commented otherwise
LAN_IP="10.0.0.13"
# The proxy host and port
PROXY_HOST="10.0.0.15"
PROXY_PORT="3142"

# if we are not using our usual gateway, we are likely not on our LAN
GATEWAY=$(ip route | grep default | awk '{print $3}')
if [ "$GATEWAY" != "$LAN_GATEWAY" ]; then
    echo "DIRECT"
    exit 0
fi

# if we are not using the static IP, we are likely not on our LAN
on_lan=false
if [ ! -z ${LAN_IP+x} ]; then
    # we are getting multiple entries. from localhost to tailscale to docker, we need to get the right one
    for ip in $(ip addr show | grep "inet " | awk '{print $2}' | cut -d '/' -f 1); do
        if [ "$ip" = "$LAN_IP" ]; then
            on_lan=true
            break
        fi
    done
    if [ "$on_lan" = false ]; then
        echo "DIRECT"
        exit 0
    fi
fi

# We are likely on our LAN, let's check if the proxy is reachable

# if the proxy is reachable, use it
if command -v nc >/dev/null 2>&1 && nc -w 1 -z "$PROXY_HOST" "$PROXY_PORT" >/dev/null 2>&1; then
    echo "http://$PROXY_HOST:$PROXY_PORT"
    exit 0
fi

# otherwise, do not use a proxy
echo "DIRECT"
exit 0